@todo

单元测试、 文档测试


	try:
		尝试执行
	except: ValueError,e:
		捕获valueError错误

	.. 捕获多种错误

	except: BaseException,e:
		捕获基类  包括所有的异常
	else:
		如果没有发生错误执行

	finally:
		最后执行 一般负责收尾工作

## 所有异常 继承自 BaseException

[常见错误类型和继承关系](https://docs.python.org/2/library/exceptions.html#exception-hierarchy)

>打印错误信息后继续执行 并正常退出

	logging.exception(e)


## 抛出错误

 	raise FooError('invalid value: %s' % s)


## 断言

	assert n != 0, 'n is zero!'

	assert的意思是，表达式n != 0应该是True，否则，后面的代码就会出错。

	如果断言失败，assert语句本身就会抛出AssertionError
		
## logging

## pdb

	python -m pdb err.py

	l 查看代码
	n 单步执行
	p 查看变量
	q 退出

> pdb.set_trace()


	# err.py
	import pdb
	
	s = '0'
	n = int(s)
	pdb.set_trace() # 运行到这里会自动暂停 c命令继续运行
	print 10 / n

	